# Site settings
title: Biocomputing Bootcamp
email: remills@umich.edu
description: > # this means to ignore newlines until "baseurl:"
   A short course at the University of Michigan introducing  
   computational tools, techniques and best practices that foster 
   reproducible research in bioinformatics, genome informatics 
   and biostatistics.
baseurl: "/bioinf606-2019" # the subpath of your site, e.g. /blog/
url: "http://dcmb-courses.github.io/bioinf606-2019" 
twitter_username: 
github_username: 
  - remills 
  - hyunminkang 
  - jhui2014 
  - bankhead3 
  - mitreac

# Build settings
markdown: kramdown
